### ISSUE TITLE
found issue on line 69

### ISSUE THREAD

**Issue by BayuYanuargi** [NationalSecurityAgency/qgis-bulk-nominatim#1]
hi,

found error python :
AttributeError: 'QgsPalLayerSettings' object has no attribute 'readFromLayer'

**Comment by BayuYanuargi** [comment]
this is full error message @hamiltoncj 

File "/Users/...../Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-bulk-nominatim-master/bulkDialog.py", line 69, in reverseGeocode
              label.readFromLayer(self.pointLayer)
             AttributeError: 'QgsPalLayerSettings' object has no attribute 'readFromLayer'

**Comment by hamiltoncj** [comment]
Thanks for contacting us. The QGIS developers kept changing the API for Pal settings in the earlier versions of QGIS 3. That is why this has shown up, but since this plugin is not being actively developed this is the first time I have known about it. The whole plugin could use an overhaul so I will check to see if people are interested in an overhaul or whether I should simply fix this issue with out an overhaul. I will get back with you on this.

**Comment by hamiltoncj** [comment]
I will be rewriting portions of this code so it may take several weeks before it is completed. I may rename the plugin as well as add other geocoders to it, but thank you for bringing this up as it brought it to the forefront that it needs to be updated.

**Comment by hamiltoncj** [comment]
@BayuYanuargi 
I went ahead and made some updates to the code base and fixed the issue you mentioned so you should be able to use it now. This was the first step, but in the next version the changes will be much more extensive. I don't know how long that is going to take me, but for now it should work for you.

**Comment by BayuYanuargi** [comment]
@hamiltoncj thanks for the effort really appreciate, will try and back to you if there any issue
