### ISSUE TITLE
Using your plugin adapted for LocationIQ

### ISSUE THREAD

**Issue by gopi-ar** [NationalSecurityAgency/qgis-bulk-nominatim#2]
Hello,

Thanks for this excellent plugin! We [forked this](https://github.com/location-iq/locationiq-qgis/pull/1) to add support for LocationIQ.com since we we host a Nominatim compatible geocoder. 

I'm writing to ask whether you'd be OK with us uploading this adaptation to the QGIS plugin repo so our users can download it directly from inside qgis? Sourcecode will remain open on GH, license is the same and of course, full credit with links to you.

Thanks in advance.

Gopi

**Comment by hamiltoncj** [comment]
Hi Gopi,

Give me a little time and I will ask those who funded the bulk-nominatim plugin. The reason I have not added that plugin myself to the QGIS plugin repo was because bulk nominatim requests to the OpenStreetMap nominatim server is prohibited. You have to set up your own nominatim server.

**Comment by gopi-ar** [comment]
Thanks!

Just to clarify, we have our own Nominatim servers, and wanted your go on whether we could upload our version (which talks to the APIs at locationiq.com) of the plugin to QGIS. We'll use a different name so there's no confusion if you decide to upload this plugin yourself in the future.

**Comment by hamiltoncj** [comment]
It might take until the end of the week before I get all comments back, but in looking at your changes it is probably not going to be a problem. Just adhere to the GNU license requirements. Also since I have users using this with their own Nominatim servers and to avoid plugin conflicts please use a plugin folder name that is different from 'bulknominatim'. We don't want to two overwriting each other. Also when reading and writing settings I am using '/BulkNominatim/...'. It would be good to use a different string from 'BulkNominatim'. I would make it related to the name of the plugin. This will also help to prevent plugin conflicts. Here is an example of getting a setting value that would need to change.

self.zoom = settings.value('/BulkNominatim/levelOfDetail', '18')

**Comment by hamiltoncj** [comment]
Go ahead and prepare your plugin to submit to the plugin repo, but rename the plugin and make the suggested changes so the two plugins don't have any conflicts. When you have it prepared, why don't you let me take a look at it so I can verify that there will be no plugin conflicts.

**Comment by gopi-ar** [comment]
Thanks @hamiltoncj ! We've made the suggested changes. It's [here](https://github.com/location-iq/locationiq-qgis/pull/1) if you'd like to take a quick look.

**Comment by hamiltoncj** [comment]
That looks good to me. Best wishes with your LocationIQ mapping business. I don't know if the Nominatim data has gotten better or not, but the last time I looked it was not very accurate on house level details. It would get you to the street and approximate where the house was at but that was the best it did. Google maps is a lot more accurate.

**Comment by gopi-ar** [comment]
Thank you for that! You're right, Nominatim primarily relies on interpolation for house level data specifically because data coverage for this is weak in OSM, but combined with other datasets like [OpenAddresses](https://github.com/openaddresses/openaddresses), accuracy for open datasets is nearly on par with Google in a lot of countries. Thanks again.
